// One-command setup for a self-hosted Sesame server.
//
//   npm run setup
//
// Generates this deployment's own signing and encryption keys, resolves the
// build contexts for the API and the two portals, and writes them to
// deploy/compose/.env. Nothing here reaches a Sesame-owned key, domain, or
// account: every secret is created locally and stays in an ignored file.
//
// Re-running is safe. A value that already exists is kept, because rotating
// the admin encryption key silently locks out every administrator whose MFA
// secret was written under the old one.

import { createPrivateKey, createPublicKey, randomBytes } from 'node:crypto'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const serverRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const composeDirectory = resolve(serverRoot, 'deploy', 'compose')
const envPath = resolve(composeDirectory, '.env')

/**
 * The portals are `web/account` and `web/admin` in the server repository. In
 * the monorepo they are still siblings of this Go module, so both layouts are
 * resolved rather than assumed.
 */
function portalContext(name) {
  for (const candidate of [resolve(serverRoot, 'web', name), resolve(serverRoot, '..', name)]) {
    if (existsSync(resolve(candidate, 'package.json'))) return candidate
  }
  return null
}

function toComposePath(absolute) {
  return relative(composeDirectory, absolute).replaceAll('\\', '/')
}

function readEnv(path) {
  const values = new Map()
  if (!existsSync(path)) return values
  for (const line of readFileSync(path, 'utf8').split(/\r?\n/)) {
    const match = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/)
    if (match) values.set(match[1], match[2].trim())
  }
  return values
}

/** Ed25519 public half of the capability signing seed, for the portal build. */
function capabilityPublicKey(seed) {
  const bytes = Buffer.from(seed, 'base64url')
  if (bytes.length !== 32 && bytes.length !== 64) return ''
  const der = Buffer.concat([
    Buffer.from('302e020100300506032b657004220420', 'hex'),
    bytes.subarray(0, 32),
  ])
  const key = createPrivateKey({ key: der, format: 'der', type: 'pkcs8' })
  const spki = createPublicKey(key).export({ format: 'der', type: 'spki' })
  return spki.subarray(spki.length - 32).toString('base64url')
}

const existing = readEnv(envPath)
const created = []
const value = (name, make) => {
  const current = existing.get(name)
  if (current) return current
  created.push(name)
  return make()
}

const secret = () => randomBytes(32).toString('base64url')
const capabilitySigningKey = value('SESAME_CAPABILITY_SIGNING_KEY', secret)
const settings = new Map([
  ['SESAME_DATABASE_PASSWORD', value('SESAME_DATABASE_PASSWORD', secret)],
  ['SESAME_CAPABILITY_SIGNING_KEY', capabilitySigningKey],
  ['SESAME_ADMIN_ENCRYPTION_KEY', value('SESAME_ADMIN_ENCRYPTION_KEY', secret)],
  ['SESAME_ADMIN_IP_PEPPER', value('SESAME_ADMIN_IP_PEPPER', secret)],
  ['SESAME_ACCOUNT_ORIGIN', value('SESAME_ACCOUNT_ORIGIN', () => 'http://localhost:4175')],
  ['SESAME_ADMIN_ORIGIN', value('SESAME_ADMIN_ORIGIN', () => 'http://localhost:4174')],
  ['SESAME_PUBLIC_SITE_ORIGIN', value('SESAME_PUBLIC_SITE_ORIGIN', () => '')],
  ['SESAME_API_ORIGIN', value('SESAME_API_ORIGIN', () => 'http://localhost:8787')],
  // The portal links back to a public site. Without one it points at itself,
  // because its runtime configuration requires an absolute origin.
  ['SESAME_SITE_ORIGIN', value('SESAME_SITE_ORIGIN', () => existing.get('SESAME_PUBLIC_SITE_ORIGIN') || 'http://localhost:4175')],
  // Only used by a deployment with no administration portal. With one, the
  // API reads the `registration_mode` feature flag from the database, which
  // is what the administration portal changes.
  ['SESAME_REGISTRATION_MODE', value('SESAME_REGISTRATION_MODE', () => 'invite')],
])

const contexts = [
  ['SESAME_SERVER_CONTEXT', serverRoot],
  ['SESAME_ACCOUNT_CONTEXT', portalContext('account')],
  ['SESAME_ADMIN_CONTEXT', portalContext('admin')],
]
const missing = contexts.filter(([, path]) => path === null).map(([name]) => name)
if (missing.length > 0) {
  console.error(`Could not find the portal sources for: ${missing.join(', ')}.`)
  console.error('Expected web/account and web/admin beside this Go module.')
  process.exit(1)
}
for (const [name, path] of contexts) settings.set(name, toComposePath(path))

settings.set('SESAME_CAPABILITY_PUBLIC_KEY', capabilityPublicKey(capabilitySigningKey))

mkdirSync(composeDirectory, { recursive: true })
const body = [
  '# Generated by `npm run setup`. Ignored by Git. These are this deployment\'s',
  '# own secrets: nothing here is shared with any other Sesame installation.',
  ...[...settings].map(([name, setting]) => `${name}=${setting}`),
  '',
].join('\n')
writeFileSync(envPath, body, { encoding: 'utf8', mode: 0o600 })

console.log(`Wrote ${toComposePath(envPath)}`)
console.log(created.length > 0
  ? `Generated ${created.length} new local secret(s): ${created.join(', ')}`
  : 'Kept every existing secret. Rotating the admin key would lock out existing administrators.')
console.log('')
console.log('Next:')
console.log('  1. docker compose -f deploy/compose/compose.yaml up --build')
console.log('  2. npm run admin:bootstrap -- bootstrap you@example.com')
console.log('  3. Open http://localhost:4175 for the account portal, 4174 for administration.')
console.log('     Local mail is at http://localhost:8025.')
