import { randomBytes } from 'node:crypto'
import { chmodSync, closeSync, fsyncSync, openSync, renameSync, unlinkSync, writeFileSync } from 'node:fs'

const ASSIGNMENT = /^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/

export function writeEnvFileAtomic(path, body, mode = 0o600) {
  const staging = `${path}.staging-${randomBytes(12).toString('hex')}`
  try {
    const descriptor = openSync(staging, 'wx', mode)
    try {
      writeFileSync(descriptor, body)
      fsyncSync(descriptor)
    } finally {
      closeSync(descriptor)
    }
    chmodSync(staging, mode)
    renameSync(staging, path)
  } catch (error) {
    try {
      unlinkSync(staging)
    } catch {
    }
    throw error
  }
}

export function parseEnvText(text) {
  const values = new Map()
  for (const line of String(text ?? '').split(/\r?\n/)) {
    const match = line.match(ASSIGNMENT)
    if (match) values.set(match[1], match[2].trim())
  }
  return values
}

// Everything the operator added by hand is carried forward verbatim. Keys that
// `npm run setup` manages are rewritten from the settings map on every run, and
// comments are dropped because the generated file owns its own header.
export function unmanagedEnvLines(text, managedNames) {
  const managed = new Set(managedNames)
  const lines = []
  for (const line of String(text ?? '').split(/\r?\n/)) {
    if (line.trim() === '' || line.trimStart().startsWith('#')) continue
    const match = line.match(ASSIGNMENT)
    if (match && managed.has(match[1])) continue
    lines.push(line)
  }
  return lines
}

export function renderEnvFile({ settings, preservedLines = [] }) {
  const body = [
    "# Generated by `npm run setup`. Ignored by Git. These are this deployment's",
    '# own secrets: nothing here is shared with any other Sesame installation.',
    ...[...settings].map(([name, setting]) => `${name}=${setting}`),
  ]
  if (preservedLines.length > 0) {
    body.push('', '# Kept from earlier runs. `npm run setup` does not manage these.', ...preservedLines)
  }
  body.push('')
  return body.join('\n')
}

export function developmentApiEnvironment(processEnv, composeEnvironment) {
  const fromCompose = (name, fallback) => processEnv[name] || composeEnvironment.get(name) || fallback
  const databasePassword = fromCompose('SESAME_DATABASE_APP_PASSWORD', 'sesame-development-only')
  return {
    ...processEnv,
    DATABASE_URL: processEnv.DATABASE_URL || `postgres://sesame_app:${encodeURIComponent(databasePassword)}@127.0.0.1:5432/sesame?sslmode=disable`,
    SESAME_API_ADDR: processEnv.SESAME_API_ADDR || '127.0.0.1:8787',
    SESAME_WEB_ORIGIN: processEnv.SESAME_WEB_ORIGIN || fromCompose('SESAME_ACCOUNT_ORIGIN', 'http://localhost:4175'),
    SESAME_SESSION_SECURE: fromCompose('SESAME_SESSION_SECURE', 'false'),
    SESAME_ADMIN_ORIGIN: fromCompose('SESAME_ADMIN_ORIGIN', 'http://localhost:4174'),
    SESAME_ADMIN_SESSION_SECURE: fromCompose('SESAME_ADMIN_SESSION_SECURE', 'false'),
    SESAME_CAPABILITY_SIGNING_KEY: fromCompose('SESAME_CAPABILITY_SIGNING_KEY', ''),
    SESAME_ADMIN_ENCRYPTION_KEY: fromCompose('SESAME_ADMIN_ENCRYPTION_KEY', ''),
    SESAME_ADMIN_IP_PEPPER: fromCompose('SESAME_ADMIN_IP_PEPPER', ''),
  }
}
