const ASSIGNMENT = /^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/

export function parseEnvText(text) {
  const values = new Map()
  for (const line of String(text ?? '').split(/\r?\n/)) {
    const match = line.match(ASSIGNMENT)
    if (match) values.set(match[1], match[2].trim())
  }
  return values
}

// Everything the operator added by hand is carried forward verbatim. Keys that
// `npm run setup` manages are rewritten from the settings map on every run, and
// comments are dropped because the generated file owns its own header.
export function unmanagedEnvLines(text, managedNames) {
  const managed = new Set(managedNames)
  const lines = []
  for (const line of String(text ?? '').split(/\r?\n/)) {
    if (line.trim() === '' || line.trimStart().startsWith('#')) continue
    const match = line.match(ASSIGNMENT)
    if (match && managed.has(match[1])) continue
    lines.push(line)
  }
  return lines
}

export function renderEnvFile({ settings, preservedLines = [] }) {
  const body = [
    "# Generated by `npm run setup`. Ignored by Git. These are this deployment's",
    '# own secrets: nothing here is shared with any other Sesame installation.',
    ...[...settings].map(([name, setting]) => `${name}=${setting}`),
  ]
  if (preservedLines.length > 0) {
    body.push('', '# Kept from earlier runs. `npm run setup` does not manage these.', ...preservedLines)
  }
  body.push('')
  return body.join('\n')
}
